# Generated by Django 3.1.2 on 2020-10-15 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profiles',
        ),
    ]
